# Generated by Django 3.0.5 on 2020-04-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='input',
            new_name='publish',
        ),
    ]
