# Generated by Django 3.0.5 on 2020-04-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20200427_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publish',
            new_name='express_publish',
        ),
    ]
