# Generated by Django 3.0.5 on 2020-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20200427_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='express_publish',
            name='slug',
            field=models.SlugField(default=404, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
